name: alphanum_sort
description: A library for Alpha Number mixed string sort
version: 0.1.0
author: Rick Zhou
homepage: https://github.com/rinick/alphanum-sort-dart

environment:
  sdk: '>=1.0.0 <2.0.0'


dev_dependencies:
  test: '>=0.12.0 <0.13.0'
